In [ ]:
pip install transformers

# allow to download, manipulate and run pre trained open source ai models

In [ ]:
from transformers import pipeline

# pipelines describes the flow of data from original to destination system

In [ ]:
import transformers
print(transformers.__version__)

4.50.0


In [ ]:
import librosa

# librosa is a python library for audio and music processing
# it can be used to extract features from audio files
# can be used to convert audio files in various wave formats like mp3, mp4, wav,etc
# can also be used to convert audio files to text


import torch

# torch is a python library for machine learning and deep learning
# it can be used to create neural networks
# it can be used to create deep learning models
# can be used for Computer Vision and Natural Language Processing


import IPython.display as display

# IPython.display is a python library for displaying data
# It can be used to display images, videos, audio, and text


from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

# Wave2Vec2ForCTC is a pytorch model for speech recognition
# Wave2Vec2Tokenizer is a pytorch tokenizer for speech recognition
# can be used to convert audio files to text(vice versa)


import numpy as np

# numpy is a python library for numerical computing
# it can be used to create arrays and matrices
# it can be used to perform mathematical operations on arrays and matrices



In [ ]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")


# tokenizer is a pytorch tokenizer for speech recognition
# model is a pytorch model for speech recognition
# facebook/wav2vec2-base-960h is a pre trained model for speech recognition
# facebook/wav2vec2-base-960h contains 960 hours of speech data
# That data is used to train the model

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
audio, sampling_rate = librosa.load("/sample.m4a", sr=16000)

<ipython-input-53-a9a66e044b5c>:1: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sampling_rate = librosa.load("/sample.m4a", sr=16000)
/usr/local/lib/python3.11/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


In [ ]:
audio, sampling_rate


(array([ 7.9213459e-12, -2.9572408e-12,  7.8403091e-12, ...,
         5.3859781e-04,  3.5790575e-04,  5.8474474e-05], dtype=float32),
 16000)

In [ ]:
display.Audio("/sample.m4a", autoplay=True)

In [ ]:
input_values = tokenizer(audio, return_tensors="pt").input_values
input_values

# input values is a pytorch tensor for speech recognition
# tokenizer(audio, return_tensors="pt") is a pytorch tokenizer for speech

tensor([[-2.7248e-05, -2.7248e-05, -2.7248e-05,  ...,  1.2877e-02,
          8.5477e-03,  1.3737e-03]])

In [ ]:
logits = model(input_values).logits
logits

# logits in tensor consists of speech data
# model(input_values).logits is a pytorch model for speech recognition

tensor([[[ 15.7895, -29.2077, -28.8371,  ...,  -7.4608,  -7.2103,  -9.3642],
         [ 16.2068, -29.5891, -29.2117,  ...,  -7.7310,  -7.5722,  -9.5448],
         [ 16.3595, -29.6562, -29.2744,  ...,  -7.7375,  -7.5627,  -9.5909],
         ...,
         [ 15.9139, -29.2852, -28.9225,  ...,  -7.6946,  -7.4231,  -9.7475],
         [ 15.9232, -29.4214, -29.0719,  ...,  -7.7345,  -7.5689,  -9.6626],
         [ 16.0360, -29.5031, -29.1586,  ...,  -7.8674,  -7.8741,  -9.6048]]],
       grad_fn=<ViewBackward0>)

In [ ]:
predicted_ids = torch.argmax(logits, dim=-1)
#predicted_ids

# torch.argmax(logits, dim=-1) means that we are taking the maximum value of the logits which is the predicted value of the speech data which says about the speech


In [ ]:
transcriptions = tokenizer.decode(predicted_ids[0])


# tokenizer.decode(predicted_ids[0]) means that we are decoding the predicted value of the speech data which was generated by the model using the tokenizer

In [ ]:
transcriptions

'HI NICE TO MEET YOU MY NAME IS BARGISHE SWARMA HOW ARE YOU DOING I HAD A GREAT TIME TO DAY'